search bar CSS
tryber/sd-09-project-frontend-online-store pull request #316
Opened 2021-03-11 23:59 UTC by Carol-Bitencourt

2021-03-12 14:45 UTC, SantosDiv requested changes

2021-03-12 14:45 UTC, SantosDiv commented on src/styles/SearchBar.css
> +.input-search-bar {
E ai Carol! O que acha de deixar as classes em ordem alfabética, para deixar no padrão Eslint? Faz sentido? 😄

2021-03-12 14:45 UTC, SantosDiv commented on src/styles/SearchBar.css
> +}
Aqui, só para o ESlint não ficar reclamando, o que acha de colocar mais uma linha? 
```suggestion
}

```

2021-03-12 14:45 UTC, SantosDiv commented on src/styles/SearchBar.css
> +    background: url(../utils/images/lupa.svg) 15px no-repeat #EDEDF0;
Gostei muito do uso do background como um SVG 😄

2021-03-12 14:45 UTC, SantosDiv commented on src/styles/SearchBar.css
> +    background: #FFFFFF;
Acho que o ESlint reclama um pouco da declaração de cores usando # ou neste caso, ele sugere, para as cores primárias, o uso do nome da cor 😄 . O que acha de trocar para `white`?
```suggestion
    background: white;
```

2021-03-12 14:45 UTC, SantosDiv commented on src/styles/SearchBar.css
> +    background: url(../utils/images/lupa.svg) 15px no-repeat #EDEDF0;
Acho que em vez de usar as cores como # (hastag), o que acha de usar com o rgb()? O ESlint não trabalha muito bem com as cores em # 😄 
```suggestion
    background: url(../utils/images/lupa.svg) 15px no-repeat rgb( 237, 237, 40 );
```

2021-03-12 14:49 UTC, SantosDiv requested changes
Parabéns Carol!! Gostei demais! Depois desses simples ajustes, tudo fica ainda mais belo! Muito bom! 🚀

2021-03-12 14:49 UTC, SantosDiv commented on src/styles/SearchBar.css
> +    width: 668px;
O que acha de deixar dois espaços de identação? Para deixar no padrão do ESlint? 😃 
```suggestion
  width: 668px;
```

2021-03-12 15:00 UTC, Carol-Bitencourt commented on src/styles/SearchBar.css
> +.input-search-bar {
Já estou ajustando, vlw ;)

2021-03-12 15:01 UTC, Carol-Bitencourt commented on src/styles/SearchBar.css
> +}
Já estou ajustando, vlw   ;)

2021-03-12 15:02 UTC, Carol-Bitencourt commented on src/styles/SearchBar.css
> +    background: #FFFFFF;
Descobri isso agora kkk

2021-03-12 15:02 UTC, Carol-Bitencourt commented on src/styles/SearchBar.css
> +    background: url(../utils/images/lupa.svg) 15px no-repeat #EDEDF0;
Blz, ajustando.

2021-03-16 15:19 UTC, pamsalesr approved these changes

2021-03-16 15:24 UTC, SantosDiv approved these changes

2021-03-16 15:25 UTC, merged