[FEAT][LIST PRODUCTS]
tryber/sd-09-project-frontend-online-store pull request #40
Opened 2021-03-09 19:42 UTC by carinebecker

Create empty product list page.

2021-03-09 21:18 UTC, BBrolesi requested changes
O código está ótimo, só fiquei com uma dúvida. 🚀

2021-03-09 21:18 UTC, BBrolesi commented on src/App.js
> +      <ProductList />
Olá @carinebecker, você não acharia melhor adicionar um Switch para já iniciar a tratativa dos paths? 🚀

2021-03-10 01:04 UTC, carinebecker commented on src/App.js
> +      <ProductList />
Sim, bem lembrado, o switch será adicionado depois quando criarmos os links das rotas. :D

2021-03-10 05:41 UTC, malves0 approved these changes
Ótimo Trabalho :+1:

2021-03-10 17:46 UTC, BBrolesi approved these changes

2021-03-10 17:48 UTC, merged