[Group-20][Req-5][Req-6]
tryber/sd-09-project-frontend-online-store pull request #419
Opened 2021-03-14 01:13 UTC by feliperocha-dev

2021-03-14 14:01 UTC, PeryclesReis commented on src/components/ProductCard.js
> +        <p>{ title }</p>
E ai belezinha!? Queria dar uma dica, o que acha de colocarmos o title e price dentro de um container afim de podermos customiza-los melhor quando for preciso?``
```suggestion
     <div>
        <p>{ title }</p>
```

2021-03-14 14:07 UTC, PeryclesReis commented on src/components/ProductCard.js
> +        <p>{ `R$ ${price}` }</p>
```suggestion
        <p>{ `R$ ${price}` }</p>
     </div>
```

2021-03-14 14:10 UTC, PeryclesReis requested changes
Eu sem querer sugeri duas mudanças iguais, foi mal, quando tiver oportunidade da uma olhadinha na minha sugestão. 😄

2021-03-14 14:23 UTC, PeryclesReis approved these changes

2021-03-14 14:23 UTC, PeryclesReis commented on src/styles/components/SearchBar.css
> +    width: 70%;
```suggestion
    margin: auto;
    width: 70%;
```

2021-03-14 14:23 UTC, PeryclesReis commented on src/components/ProductCard.js
> +     <div>
```suggestion
```

2021-03-15 13:31 UTC, ped-alm2709 approved these changes

2021-03-16 14:10 UTC, merged