[Grupo 28] - Requisito 11
tryber/sd-09-project-frontend-online-store pull request #523
Opened 2021-03-17 23:59 UTC by brenno-calado

os comentários estão sendo salvos e renderizados na pagina de detalhes. Só está faltando modificar a forma de salvar e puxar do localStorage para que os comentários sejam para cada produto clicado.

2021-03-18 14:36 UTC, Henrique-Moura requested changes
Parabéns pela dedicação Brenno!

2021-03-18 14:36 UTC, Henrique-Moura commented on src/components/ProductDetails.js
> +        <input
Fala, Brenno. O que acha de colocarmos uma validação de email. Caso acha interessante, dá uma olhada neste link [aqui.](https://github.com/alexandreservian/regex-cheat-sheet#valida%C3%A7%C3%A3o-de-email)

2021-03-18 14:36 UTC, Henrique-Moura commented on src/components/ProductDetails.js
> +          placeholder="ribeiro.brito@google.com"
Como não temos uma label indicado o que é o campo, não seria melhor que o placeholder fizesse isso? Então ao invés de passarmos um e-mail, colocarmos a palavra e-mail? 
```suggestion
          placeholder="Email"
```

2021-03-18 14:36 UTC, Henrique-Moura commented on src/components/ProductDetails.js
> +        />
Brenno, percebi que o campo email não está como obrigatório, caso não seja preenchido nada, o que renderiza na página?

2021-03-19 00:21 UTC, brenno-calado commented on src/components/ProductDetails.js
> +        />
Implementado o required!

2021-03-19 00:37 UTC, Henrique-Moura approved these changes

2021-03-19 00:38 UTC, PPiquini approved these changes
Ficou muito bom! Aprovado!

2021-03-19 00:38 UTC, merged